[package]
name = "saarathi-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
sqlx = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
axum = { workspace = true }
jsonwebtoken = { workspace = true }
anyhow = { workspace = true }
h3o = { workspace = true }
geo = { workspace = true }
redis = { workspace = true }
async-nats = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true }
